### Numpy Practice session

In [2]:
# Import libraries
import numpy as np


### Creating an Array using Numpy

In [4]:
food=np.array(["Pakora","Samosa","Raita"])
food

array(['Pakora', 'Samosa', 'Raita'], dtype='<U6')

In [5]:
price=np.array([5,5,5])
price

array([5, 5, 5])

In [6]:
type(price)

numpy.ndarray

In [7]:
type(food)

numpy.ndarray

In [9]:
len(food)

3

In [10]:
price[0:]

array([5, 5, 5])

In [11]:
food[1]

'Samosa'

In [12]:
price.mean()

5.0

In [14]:
# Zero Method
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [15]:
# Ones Array
np.ones(5)

array([1., 1., 1., 1., 1.])

In [16]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
# specify
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [18]:
# specific interval
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [19]:
#Table of five
np.arange(5,55,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [20]:
# Line space
np.linspace(1,100,num=10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [22]:
# specify datatypes
np.ones(5,dtype=np.int64)

array([1, 1, 1, 1, 1], dtype=int64)

In [23]:
# specify datatypes
np.ones(5,dtype=np.float64)

array([1., 1., 1., 1., 1.])

## Functions of Arrays

In [25]:
a=np.array([10,12,15,2,4,6,100,320,0.5,10.5])
a

array([ 10. ,  12. ,  15. ,   2. ,   4. ,   6. , 100. , 320. ,   0.5,
        10.5])

In [26]:
a.sort()

In [27]:
b=np.array([10.2,2.5,3.,23.2,76.2,45.5])
b

array([10.2,  2.5,  3. , 23.2, 76.2, 45.5])

In [28]:
c=np.concatenate((a,b))
c

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.5,  12. ,  15. , 100. ,
       320. ,  10.2,   2.5,   3. ,  23.2,  76.2,  45.5])

In [34]:
c.sort()
c

array([  0.5,   2. ,   2.5,   3. ,   4. ,   6. ,  10. ,  10.2,  10.5,
        12. ,  15. ,  23.2,  45.5,  76.2, 100. , 320. ])

## 2-D Arrays

In [37]:
a=np.array([[1,2,3,4],[4,3,2,1]])
a

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [40]:
b=np.array([[5,6,7,8],[9,10,11,12]])
b

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [42]:
c=np.concatenate((a,b))
c

array([[ 1,  2,  3,  4],
       [ 4,  3,  2,  1],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [45]:
c=np.concatenate((a,b),axis=1)
c

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 4,  3,  2,  1,  9, 10, 11, 12]])